name: MyPCGAN
channels:
  - defaults
dependencies:
  - python==3.9
  - scipy==1.9.3
  - tqdm==4.64.1
  - librosa==0.9.2
  - numpy==1.23.4
  - pandas==1.4.2
  - torchvision==0.14.0
  - torchaudio==0.13.0
  - pytorch==1.13.0
  - wandb
